# Generated by Django 3.2.9 on 2021-12-04 08:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CataxDBnew',
            fields=[
                ('txnID', models.CharField(default=uuid.uuid4, editable=False, max_length=300, primary_key=True, serialize=False)),
                ('accountID', models.CharField(max_length=20)),
                ('accountType', models.CharField(max_length=10)),
                ('userID', models.CharField(blank=True, max_length=20)),
                ('txnEntryRoute', models.CharField(blank=True, max_length=10)),
                ('txn', models.CharField(blank=True, max_length=20)),
                ('txnType', models.CharField(blank=True, max_length=10, null=True)),
                ('txnSubType', models.CharField(blank=True, max_length=10, null=True)),
                ('txnClaimedDateTime', models.DateTimeField(blank=True, null=True)),
                ('txnExchangeDate', models.CharField(blank=True, max_length=100, null=True)),
                ('exchangeTxnID', models.CharField(blank=True, max_length=500, null=True)),
                ('fees', models.FloatField(blank=True, default=0, null=True)),
                ('feeCurrency', models.CharField(blank=True, max_length=100, null=True)),
                ('txnHash', models.CharField(blank=True, max_length=500, null=True)),
                ('txnCustomerMemo', models.TextField(blank=True, null=True)),
                ('txnExchangeMemo', models.TextField(blank=True, null=True)),
                ('txnAuditorMemo', models.TextField(blank=True, null=True)),
                ('txnStatus', models.CharField(blank=True, max_length=50, null=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('updatedOn', models.DateTimeField(blank=True, null=True)),
                ('txnVersion', models.SmallIntegerField(blank=True, null=True)),
                ('creditedCoins', models.FloatField(blank=True, null=True)),
                ('creditCurrency', models.CharField(blank=True, max_length=50, null=True)),
                ('creditBaseAmount', models.FloatField(blank=True, null=True)),
                ('creditBaseCurrency', models.CharField(blank=True, max_length=50, null=True)),
                ('debitedFromAccountID', models.CharField(blank=True, max_length=100, null=True)),
                ('toCryptoWallet', models.CharField(blank=True, max_length=1000, null=True)),
                ('debitCoins', models.FloatField(blank=True, null=True)),
                ('debitCurrency', models.CharField(blank=True, max_length=50, null=True)),
                ('debitBaseAmount', models.FloatField(blank=True, null=True)),
                ('debitBaseCurrency', models.CharField(blank=True, max_length=50, null=True)),
                ('creditedToAccountID', models.CharField(blank=True, max_length=100, null=True)),
                ('fromCryptoWallet', models.CharField(blank=True, max_length=1000, null=True)),
                ('isReconciled', models.BooleanField(default=0)),
                ('isDeleted', models.BooleanField(default=0)),
                ('isAnalyzed', models.BooleanField(default=0)),
                ('totalValueofTransaction', models.FloatField(blank=True, null=True)),
                ('totalValueCurrency', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
